pythonPath <- "/p/projects/rd3mod/python/environments/scm_magicc7_hpc"
cat("################\n")
cat("#### PYTHON ####\n")
cat("################\n")
cat(paste0("PYTHON ENVIRONMENT on host '", system2("hostname", stdout = TRUE), "'\n"))
cat(paste0("pythonPath = '", pythonPath, "'\n"))
cat(paste0("source activate ", pythonPath, "'\n"))
# system2("source", c("activate", pythonPath), stdout = TRUE)
# system("source activate /p/projects/rd3mod/python/environments/scm_magicc7_hpc/; which python")
system("echo 'WHAT?'")
cat(paste0("which python           '", system2("which", c("python"), stdout = TRUE), "'\n"))
cat(paste0("Sys.which('python')    '", Sys.which("python"), "'\n"))
cat(paste0("python --version       '", system2("python", c("--version"), stdout = TRUE), "'\n"))
cat(paste0("Can import?             ", system2("python", c("-c", "'import climate_assessment; print(\"Yes!\")'"), stdout = TRUE), "\n"))
cat("################\n")