on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description
        id: check_pr_template
        run: echo "The description of your PR is ${{ github.event.pull_request.body }}"

