on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description
        id: check_pr_template
        run: |
           PR_DESCRIPTION='${{ github.event.pull_request.body }}'
           TYPE_OF_CHANGE_SECTION=$(echo "$PR_DESCRIPTION" | sed -n '/## Type of change/,/## Checklist:/p')
           echo "$TYPE_OF_CHANGE_SECTION"

