on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description
        id: check_pr_template
        run: | 
          printf "The description of your PR is:\n%s\n" "${{ github.event.pull_request.body }}"

