name: PR Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.AUTO_DEV_VERSION_REMIND }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2
        with:
          token: ${{ secrets.AUTO_DEV_VERSION_REMIND }}

      - name: Check PR description
        id: check_pr
        run: |
          FILE="pull_request_template.md"
          TYPE_OF_CHANGE_SECTION=$(awk '/## Type of change/,/## Checklist:/' "$FILE")
          if echo "$TYPE_OF_CHANGE_SECTION" | grep -q "\[ \]"; then
            echo "Unselected checkboxes found in the 'Type of change' section of the pull request description. Please delete unselected items in this section."
            exit 1
          fi

      - name: Set PR status
        if: failure()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Unselected checkboxes found in the 'Type of change' section. Please delete unselected items in this section."