on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description
        id: check_pr_template
        run: |
           pr_body='${{ github.event.pull_request.body }}'
           echo "$pr_body"

